### ISSUE TITLE
Unhandled exception executing command 'rtp'

### ISSUE THREAD

**Issue by Superkooka** [Oerthyon/FactionItems#1]
```
[15:24:50 INFO]: TheMachuPichu issued server command: /rtp
[15:24:50 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rtp' in plugin Factionitems v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.IllegalArgumentException: Random range is empty: [-1000.0, -1000.0).
        at kotlin.random.RandomKt.checkRangeBounds(Random.kt:344) ~[?:?]
        at kotlin.random.Random.nextDouble(Random.kt:173) ~[?:?]
        at kotlin.random.Random$Default.nextDouble(Random.kt:257) ~[?:?]
        at com.superkooka.oerthyon.factionitems.randomtp.RandomTPCommand.findValidLocationInOverworld(RandomTPCommand.kt:126) ~[?:?]
        at com.superkooka.oerthyon.factionitems.randomtp.RandomTPCommand.onCommand(RandomTPCommand.kt:75) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 15 more
```

**Comment by Superkooka** [comment]
fix in https://github.com/Oerthyon/FactionItems/commit/291753b4948ed887bd945848f51205681ec2aabe
